version: '3.9'

services:
  newrelic-infra:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra
    privileged: true
    pid: host
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./newrelic-infra/newrelic-infra.yml:/etc/newrelic-infra.yml:ro
    restart: unless-stopped
    networks:
        - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: "reverse-proxy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ./nginx-proxy-manager/data/certbot:/var/www/certbot
    depends_on:
      - snippet_service
      - auth_service
    networks:
        - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ./nginx-proxy-manager/data/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"
    networks:
        - app_network

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=ingsisg10
      - TOKEN=${DUCK_DNS_TOKEN}
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./duckdns:/config

  snippet_service:
    container_name: "snippet_service_infra"
    image: ghcr.io/ingsisg10/snippet-service:latest
    expose:
      - "8080"
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    networks:
      - app_network

  auth_service:
    container_name: "auth_service_infra"
    image: ghcr.io/ingsisg10/auth-service:latest
    expose:
      - "8080"
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    networks:
      - app_network

#  ui:
#    container_name: "printscript_ui_infra"
#    build: ./ui-server
#    volumes:
#      - ./ui:/usr/share/nginx/html:ro

networks:
  app_network:
    driver: bridge
