version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: "reverse-proxy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81" # to check nginx
      - "443:443"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html:ro
      - ./nginx/certs:/etc/letsencrypt:ro
    depends_on:
      - snippet_service
      - auth_service
      # - ui

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/static:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do
        certbot certonly --webroot -w /var/www/certbot
          -d ingsisg10.duckdns.org
          --email acunacarlos283@gmail.com
          --agree-tos --non-interactive;
        sleep 12h;
      done"


  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=ingsisg10.duckdns.org
      - TOKEN=${DUCK_DNS_TOKEN}
      - TZ = America/Argentina/Buenos_Aires
    volumes:
      - ./duckdns:/config


  snippet_service:
    container_name: "snippet_service_infra"
    image: nginx
    volumes:
      - ./snippet-service/:/usr/share/nginx/html:ro

  auth_service:
    container_name: "auth_service_infra"
    image: nginx
    volumes:
      - ./auth-service/:/usr/share/nginx/html:ro

#  ui:
#    container_name: "printscript_ui_infra"
#    build: ./ui-server
#    volumes:
#      - ./ui:/usr/share/nginx/html:ro
