version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: "reverse-proxy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: "certbot"
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
      - ./nginx/conf:/etc/nginx/conf.d
    # El comando se ejecuta al iniciar el contenedor.
    command: >
      sh -c "
        while true; do
          certbot renew --quiet --webroot --webroot-path=/var/www/certbot \
            --post-hook 'nginx -s reload'
          sleep 12h
        done
      "
    networks:
      - app_network

  # ... (Tus otros servicios)
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=ingsisg10
      - TOKEN=${DUCK_DNS_TOKEN}
    volumes:
      - ./duckdns:/config

  snippet_service:
    container_name: "snippet_service_infra"
    image: ghcr.io/ingsisg10/snippet-service:latest
    expose:
      - "8080"
    networks:
      - app_network

  auth_service:
    container_name: "auth_service_infra"
    image: ghcr.io/ingsisg10/auth-service:latest
    expose:
      - "8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge