name: docker-img-to-ghcr-dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag de la imagen (ej. v1.2.3)"
        required: false
        default: latest

  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: latest

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags (dev)
        id: tags
        run: |
          # Extraer owner y repo del repo actual
          OWNER="$(echo '${{ github.repository }}' | cut -d'/' -f1)"
          REPO="$(echo '${{ github.repository }}' | cut -d'/' -f2)"

          # Nombre dev
          REPO_DEV="${REPO}-dev"

          IMAGE="ghcr.io/${OWNER}/${REPO_DEV}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')

          TAG="${{ inputs.tag || 'latest' }}"

          echo "IMAGE=$IMAGE"
          echo "TAG=$TAG"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG"     >> "$GITHUB_OUTPUT"

      - name: Build & Push (dev)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          build-args: |
            GITHUB_ACTOR=${{ github.actor }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: |
            ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
            ${{ steps.tags.outputs.image }}:${{ github.sha }}
          secrets: |
            gpr_user=${{ github.actor }}
            gpr_key=${{ secrets.GITHUB_TOKEN }}