name: frontend-to-ghcr-dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag de la imagen (ej. v1.2.3)"
        required: false
        default: latest

  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: latest
    secrets:
      VITE_AUTH0_DOMAIN:
        required: true
      VITE_AUTH0_CLIENT_ID:
        required: true
      VITE_AUTH0_AUDIENCE:
        required: true
      VITE_FRONTEND_URL:
        required: false
      VITE_BACKEND_URL:
        required: false
      VITE_NGINX_URL:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags (dev)
        id: tags
        run: |
          OWNER="$(echo '${{ github.repository }}' | cut -d'/' -f1)"
          REPO="$(echo '${{ github.repository }}' | cut -d'/' -f2)"

          REPO_DEV="${REPO}-dev"

          IMAGE="ghcr.io/${OWNER}/${REPO_DEV}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')

          TAG="${{ inputs.tag || 'latest' }}"

          echo "IMAGE=$IMAGE"
          echo "TAG=$TAG"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG"     >> "$GITHUB_OUTPUT"

      - name: Build & Push (dev)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
            VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}
            VITE_FRONTEND_URL=${{ 'https://grupo10ingsis-dev.duckdns.org' }}
            VITE_BACKEND_URL=${{ 'https://grupo10ingsis-dev.duckdns.org' }}
            VITE_NGINX_URL=${{ secrets.VITE_NGINX_URL }}
          push: true
          tags: |
            ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
            ${{ steps.tags.outputs.image }}:${{ github.sha }}